/**
 * End-of-story flow: Quiz (4 interleaved questions) → Summary.
 *
 * Quiz items are generated by the story LLM at story creation and stored
 * on the Story (with a lazy backfill endpoint for legacy stories). Each
 * answer + reveal is persisted via /stories/{id}/quiz/attempts so future
 * SRS personalisation has the data.
 *
 * Summary surfaces the day's takeaway:
 *  - Hero: stats from this session (sentences pronounced, clarity %, quiz score).
 *  - Souvenir: a single sentence the user nailed today (heuristic on the
 *    in-memory scoresBySentence — best `good` count, tie-break longest).
 *  - Schedule: target words with a heuristic "next review" label
 *    (struggled-today gets bumped to próxima sesión).
 *  - Insight: LLM-generated linguistic note about the story; fetched async
 *    with a skeleton; cached on the Story after first fetch.
 *  - NextSteps: Another story / Re-read / Home.
 */

import { useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { api } from "../api/client";
import type {
  ClozeQuizItem,
  GenderClozeQuizItem,
  InsightResponse,
  KlaraNoteResponse,
  L1GenderNote,
  MCQuizItem,
  QuizItem,
  ScheduleBucket,
  ScheduleEntry,
  ShadowQuizItem,
  Story,
  StoryWord,
} from "../api/types";
import GenderPicker from "./GenderPicker";
import { startAudioBars } from "../lib/audioBars";
import { startMicRecording, type MicRecorder, type ScoreBand } from "../lib/pronunciation";
import { startSilenceDetector } from "../lib/silenceDetector";
import { speak, stop as stopTTS } from "../lib/tts";
import { useMicScorer } from "../lib/useMicScorer";

type PronScores = Record<number, ScoreBand>;

interface Props {
  story: Story;
  scoresBySentence: Record<number, PronScores>;
  reviewIds: Set<string>;
  adding: string | null;
  onToggleReview: (word: StoryWord) => void;
  onRestart: () => void;
  onNew: () => void;
  onNextInModule?: () => void;
  onHome: () => void;
  /** Fired once per transition into the summary view (spec §4/§9: the
   * "historia completada" event fires at the Finish SUMMARY, not at quiz
   * entry). Backend is idempotent, so a StrictMode double-invoke is fine. */
  onSummaryShown?: () => void;
}

interface QuizResult {
  index: number;
  qType: "mc" | "cloze" | "shadow" | "gender_cloze";
  correct: boolean;
  revealed: boolean;
}

export default function StoryFinish({
  story,
  scoresBySentence,
  reviewIds,
  adding,
  onToggleReview,
  onRestart,
  onNew,
  onNextInModule,
  onHome,
  onSummaryShown,
}: Props): JSX.Element {
  const { t } = useTranslation();
  const [view, setView] = useState<"quiz" | "summary">("quiz");
  const [quizItems, setQuizItems] = useState<QuizItem[] | null>(null);
  const [quizError, setQuizError] = useState<boolean>(false);
  const [quizResults, setQuizResults] = useState<QuizResult[]>([]);

  // Fire once per transition into the summary view. Deliberately not
  // depending on onSummaryShown (Story.tsx passes an inline callback, so its
  // identity changes on every parent re-render) — only `view` flipping to
  // "summary" should re-fire this.
  useEffect(() => {
    if (view === "summary") onSummaryShown?.();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [view]);

  // Load quiz items on mount. If the backend returns an empty list (LLM
  // gen failed for some reason), skip directly to the summary.
  useEffect(() => {
    let cancelled = false;
    api
      .getStoryQuiz(story.id)
      .then((r) => {
        if (cancelled) return;
        if (!r.items || r.items.length === 0) {
          setView("summary");
          setQuizError(true);
          return;
        }
        setQuizItems(r.items);
      })
      .catch(() => {
        if (cancelled) return;
        setQuizError(true);
        setView("summary");
      });
    return () => {
      cancelled = true;
      stopTTS();
    };
  }, [story.id]);

  if (view === "summary") {
    return (
      <Summary
        story={story}
        scoresBySentence={scoresBySentence}
        quizResults={quizResults}
        quizSkipped={quizError}
        reviewIds={reviewIds}
        adding={adding}
        onToggleReview={onToggleReview}
        onRestart={onRestart}
        onNew={onNew}
        onNextInModule={onNextInModule}
        onHome={onHome}
        onBackToQuiz={quizError ? null : () => setView("quiz")}
      />
    );
  }

  if (quizItems === null) {
    return (
      <main className="k-page finish-flow">
        <p className="fin-back k-mono">{t("common.loading")}</p>
      </main>
    );
  }

  return (
    <main className="k-page finish-flow">
      <button type="button" className="fin-back" onClick={onHome}>
        {t("common.backHome")}
      </button>
      <Quiz
        items={quizItems}
        story={story}
        onComplete={(results) => {
          setQuizResults(results);
          setView("summary");
          window.scrollTo({ top: 0, behavior: "instant" });
        }}
      />
    </main>
  );
}

/* ============================================================
   QUIZ
   ============================================================ */

interface QuizProps {
  items: QuizItem[];
  story: Story;
  onComplete: (results: QuizResult[]) => void;
}

function Quiz({ items, story, onComplete }: QuizProps): JSX.Element {
  const [idx, setIdx] = useState(0);
  const [results, setResults] = useState<QuizResult[]>([]);

  const total = items.length;
  const q = items[idx];
  const isLast = idx === total - 1;

  const onAnswered = (r: Omit<QuizResult, "index" | "qType">) => {
    const full: QuizResult = { index: idx, qType: q.type, ...r };
    setResults((rs) => [...rs, full]);
    // Best-effort persistence — failures don't block the UX. Gender items
    // record their own diadic evidence (recordGenderAttempt), so skip the
    // generic quiz-attempt record for them.
    if (q.type !== "gender_cloze") {
      void api
        .recordQuizAttempt(story.id, {
          question_index: idx,
          question_type: q.type,
          was_correct: full.correct,
          was_revealed: full.revealed,
        })
        .catch(() => undefined);
    }
  };

  const onNext = () => {
    if (isLast) onComplete(results);
    else setIdx((i) => i + 1);
  };

  return (
    <>
      <QuizHero idx={idx} total={total} />
      <div className="qstage" key={idx /* remount each q for clean state */}>
        {q.type === "mc" && (
          <MCQuestion
            q={q}
            story={story}
            onAnswered={onAnswered}
            onNext={onNext}
            isLast={isLast}
          />
        )}
        {q.type === "cloze" && (
          <ClozeQuestion
            q={q}
            story={story}
            onAnswered={onAnswered}
            onNext={onNext}
            isLast={isLast}
          />
        )}
        {q.type === "shadow" && (
          <ShadowQuestion
            q={q}
            story={story}
            onAnswered={onAnswered}
            onNext={onNext}
            isLast={isLast}
          />
        )}
        {q.type === "gender_cloze" && (
          <GenderClozeQuestion
            q={q}
            story={story}
            onAnswered={onAnswered}
            onNext={onNext}
            isLast={isLast}
          />
        )}
      </div>
    </>
  );
}

function QuizHero({ idx, total }: { idx: number; total: number }): JSX.Element {
  const { t } = useTranslation();
  return (
    <header className="quiz-hero">
      <h1 className="quiz-hero__title">{t("story.finish.quiz.title")}</h1>
      <p className="quiz-hero__sub">{t("story.finish.quiz.sub")}</p>
      <div className="quiz-hero__prog">
        <span className="quiz-hero__count">
          {String(idx + 1).padStart(2, "0")}{" "}
          <span className="quiz-hero__slash">/</span> {String(total).padStart(2, "0")}
        </span>
        <div className="quiz-hero__track">
          {Array.from({ length: total }).map((_, i) => (
            <span
              key={i}
              className="quiz-hero__pip"
              data-state={i < idx ? "done" : i === idx ? "now" : "next"}
            />
          ))}
        </div>
      </div>
    </header>
  );
}

/* ============================================================
   MC question — voice-pick (mic transcribes + fuzzy-matches the option)
   with tap as accessibility fallback.
   ============================================================ */

interface MCProps {
  q: MCQuizItem;
  story: Story;
  onAnswered: (r: Omit<QuizResult, "index" | "qType">) => void;
  onNext: () => void;
  isLast: boolean;
}

type MCMicPhase = "idle" | "recording" | "resolving" | "no_match";

function MCQuestion({ q, story, onAnswered, onNext, isLast }: MCProps): JSX.Element {
  const { t } = useTranslation();
  const [picked, setPicked] = useState<number | null>(null);
  const [revealed, setRevealed] = useState(false);
  const [micPhase, setMicPhase] = useState<MCMicPhase>("idle");
  const [lastTranscript, setLastTranscript] = useState<string>("");
  const recorderRef = useRef<MicRecorder | null>(null);
  const recAnalyserRef = useRef<AnalyserNode | null>(null);
  const recBarsRef = useRef<HTMLSpanElement[]>([]);
  const answered = picked !== null;

  const onTap = (i: number) => {
    if (answered || micPhase !== "idle") return;
    setPicked(i);
    onAnswered({ correct: i === q.correct, revealed: false });
  };
  const onReveal = () => {
    if (answered) return;
    cancelMic();
    setPicked(q.correct);
    setRevealed(true);
    onAnswered({ correct: false, revealed: true });
  };

  function cancelMic() {
    recorderRef.current?.cancel();
    recorderRef.current = null;
    recAnalyserRef.current = null;
    setMicPhase("idle");
  }

  async function startMic() {
    if (micPhase !== "idle" && micPhase !== "no_match") return;
    setLastTranscript("");
    try {
      const rec = await startMicRecording();
      recorderRef.current = rec;
      recAnalyserRef.current = rec.analyser;
      setMicPhase("recording");
    } catch {
      setMicPhase("idle");
    }
  }

  async function stopMic() {
    const rec = recorderRef.current;
    if (rec === null || micPhase !== "recording") return;
    recorderRef.current = null;
    recAnalyserRef.current = null;
    setMicPhase("resolving");
    try {
      const blob = await rec.stop();
      if (!blob || blob.size === 0) {
        setMicPhase("no_match");
        return;
      }
      const resp = await api.resolveMC(
        story.id,
        blob,
        q.options,
        story.target_language,
      );
      setLastTranscript(resp.transcript);
      if (resp.picked_index !== null) {
        setPicked(resp.picked_index);
        onAnswered({ correct: resp.picked_index === q.correct, revealed: false });
      } else {
        setMicPhase("no_match");
      }
    } catch {
      setMicPhase("no_match");
    } finally {
      // The "no_match" branch leaves micPhase as-is; the success branch
      // already set picked which hides the mic UI. Only the resolving →
      // happy-path needs idle reset, but setting it here unconditionally
      // is harmless because answered hides this whole block.
      if (recorderRef.current === null && !answered) {
        // Leave phase alone — either we picked (UI hides) or no_match (shown).
      }
    }
  }

  function tryAgain() {
    setMicPhase("idle");
    setLastTranscript("");
  }

  // Live RMS bars while recording
  useEffect(() => {
    if (micPhase !== "recording" || !recAnalyserRef.current) return;
    const analyser = recAnalyserRef.current;
    return startAudioBars(analyser, recBarsRef.current);
  }, [micPhase]);

  // Primary stop trigger: 1.5s of silence after the user has had ≥800ms
  // to start speaking. Falls back to a 20s hard timeout in case the
  // silence detector misbehaves (e.g. flaky mic feeding garbage samples).
  useEffect(() => {
    if (micPhase !== "recording" || !recAnalyserRef.current) return;
    const cleanupSilence = startSilenceDetector(recAnalyserRef.current, () => {
      void stopMic();
    });
    const safety = window.setTimeout(() => void stopMic(), 20_000);
    return () => {
      cleanupSilence();
      clearTimeout(safety);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [micPhase]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      recorderRef.current?.cancel();
      recorderRef.current = null;
    };
  }, []);

  return (
    <article className="qcard" data-type="mc">
      <header className="qcard__head">
        <span className="fin-cap">{q.cap}</span>
      </header>
      <div className="qcard__body">
        <p className="qcard__prompt qcard__prompt--lg">{q.prompt}</p>
        <ul className="qcard__opts">
          {q.options.map((opt, i) => {
            let state = "idle";
            if (answered) {
              if (i === picked && i === q.correct && !revealed) state = "correct";
              else if (i === picked && i !== q.correct) state = "wrong";
              else if (i === q.correct && revealed) state = "reveal";
              else if (i === q.correct) state = "correct";
              else state = "muted";
            }
            return (
              <li key={i}>
                <button
                  type="button"
                  className="qcard__opt"
                  data-state={state}
                  onClick={() => onTap(i)}
                  disabled={answered || micPhase === "recording" || micPhase === "resolving"}
                >
                  <span className="qcard__opt-letter">
                    {String.fromCharCode(65 + i)}
                  </span>
                  <span className="qcard__opt-text">{opt}</span>
                  {state === "correct" && <span className="qcard__opt-mark">✓</span>}
                  {state === "wrong" && <span className="qcard__opt-mark">✗</span>}
                  {state === "reveal" && <span className="qcard__opt-mark">→</span>}
                </button>
              </li>
            );
          })}
        </ul>
      </div>
      <footer className="qcard__foot">
        {!answered && micPhase === "idle" && (
          <div className="qcard__voicebar">
            <span className="qcard__hint">{t("story.finish.quiz.mc.readAloud")}</span>
            <div className="qcard__actions">
              <button type="button" className="qcard__ghost" onClick={onReveal}>
                {t("story.finish.quiz.reveal")}
              </button>
              <button type="button" className="qcard__mic" onClick={() => void startMic()}>
                <span className="fin-mic" />
                <span>{t("story.finish.quiz.yourTurn")}</span>
              </button>
            </div>
          </div>
        )}

        {micPhase === "recording" && (
          <div className="qcard__rec" role="status" aria-live="polite" onClick={() => void stopMic()} style={{ cursor: "pointer" }}>
            <span className="qcard__rec-dot" />
            <span className="qcard__rec-bars" aria-hidden="true">
              {Array.from({ length: 16 }).map((_, i) => (
                <span
                  key={i}
                  className="qcard__rec-bar"
                  ref={(el) => {
                    if (el) recBarsRef.current[i] = el;
                  }}
                  style={{ height: "30%" }}
                />
              ))}
            </span>
            <span className="qcard__rec-lbl">{t("story.sentence.listening")}</span>
          </div>
        )}

        {micPhase === "resolving" && (
          <div className="qcard__eval" role="status" aria-live="polite">
            <span className="qcard__eval-spin" aria-hidden="true" />
            <span className="qcard__eval-lbl">{t("story.sentence.evaluating")}</span>
          </div>
        )}

        {micPhase === "no_match" && (
          <div className="qcard__voicebar">
            <span className="qcard__hint">
              {lastTranscript
                ? t("story.finish.quiz.mc.heardButNoMatch", { transcript: lastTranscript })
                : t("story.finish.quiz.mc.noSpeech")}
            </span>
            <div className="qcard__actions">
              <button type="button" className="qcard__ghost" onClick={onReveal}>
                {t("story.finish.quiz.reveal")}
              </button>
              <button type="button" className="qcard__mic" onClick={tryAgain}>
                <span className="fin-mic" />
                <span>{t("story.finish.quiz.mc.tryAgain")}</span>
              </button>
            </div>
          </div>
        )}
        {answered && (
          <>
            {q.after && <p className="qcard__after">{q.after}</p>}
            <button
              type="button"
              className="fin-btn fin-btn--primary qcard__next"
              onClick={onNext}
            >
              {isLast ? t("story.finish.quiz.toSummary") : t("story.finish.quiz.next")}{" "}
              <span className="fin-arr">→</span>
            </button>
          </>
        )}
      </footer>
    </article>
  );
}

/* ============================================================
   Cloze question — sentence with a blank, user speaks the word.
   ============================================================ */

interface ClozeProps {
  q: ClozeQuizItem;
  story: Story;
  onAnswered: (r: Omit<QuizResult, "index" | "qType">) => void;
  onNext: () => void;
  isLast: boolean;
}

function ClozeQuestion({
  q,
  story,
  onAnswered,
  onNext,
  isLast,
}: ClozeProps): JSX.Element {
  const { t } = useTranslation();
  const scorer = useMicScorer(q.answer, story.target_language);
  const [revealed, setRevealed] = useState(false);
  const recBarsRef = useRef<HTMLSpanElement[]>([]);

  const filled = revealed || (scorer.phase === "scored" && Boolean(scorer.result));
  // Cloze "correct" threshold: Azure pronunciation score >= 60 AND the
  // recognized word matches the answer (case-insensitive, accent-relaxed).
  const isCorrect =
    scorer.result != null &&
    scorer.result.overallScore >= 60 &&
    matchesLoose(scorer.result.recognizedText, q.answer);

  // Live RMS bars while recording — exactly like SentenceView.
  useEffect(() => {
    if (scorer.phase !== "recording" || !scorer.analyser) return;
    const analyser = scorer.analyser;
    return startAudioBars(analyser, recBarsRef.current);
  }, [scorer.phase, scorer.analyser]);

  // Fire the attempt record + bubble result up once scoring lands.
  const reportedRef = useRef(false);
  useEffect(() => {
    if (scorer.phase !== "scored" || !scorer.result || reportedRef.current) return;
    reportedRef.current = true;
    onAnswered({ correct: isCorrect, revealed: false });
    void api
      .recordPronunciationAttempt(story.id, {
        sentence_index: -1, // -1 marks "quiz cloze" not a story sentence
        reference_text: q.answer,
        recognized_text: scorer.result.recognizedText,
        overall_score: scorer.result.overallScore,
        word_bands: Object.fromEntries(
          Object.entries(scorer.result.bands).map(([k, v]) => [k, v]),
        ),
      })
      .catch(() => undefined);
  }, [
    isCorrect,
    onAnswered,
    q.answer,
    scorer.phase,
    scorer.result,
    story.id,
  ]);

  const onReveal = () => {
    if (filled || scorer.phase !== "idle") return;
    setRevealed(true);
    onAnswered({ correct: false, revealed: true });
  };

  const onMicClick = () => {
    if (scorer.phase === "recording") void scorer.stop();
    else if (scorer.phase === "idle" || scorer.phase === "error") void scorer.start();
  };

  return (
    <article className="qcard" data-type="cloze">
      <header className="qcard__head">
        <span className="fin-cap">{q.cap}</span>
      </header>
      <div className="qcard__body">
        <p className="qcard__klara-line">{t("story.finish.quiz.cloze.klaraSays")}</p>
        <p className="qcard__cloze">
          <span>{q.sentence_pre}</span>
          <span
            className="qcard__blank"
            data-state={
              filled
                ? revealed
                  ? "revealed"
                  : isCorrect
                    ? "correct"
                    : "revealed"
                : "empty"
            }
          >
            {filled ? q.answer : <span className="qcard__blank-rule" />}
          </span>
          <span>{q.sentence_post}</span>
        </p>
        {q.en && <p className="qcard__en">{q.en}</p>}
      </div>
      <footer className="qcard__foot">
        {scorer.phase === "idle" && !filled && (
          <>
            {q.hint && <span className="qcard__hint">{q.hint}</span>}
            <div className="qcard__actions">
              <button type="button" className="qcard__ghost" onClick={onReveal}>
                {t("story.finish.quiz.reveal")}
              </button>
              <button type="button" className="qcard__mic" onClick={onMicClick}>
                <span className="fin-mic" />
                <span>{t("story.finish.quiz.yourTurn")}</span>
              </button>
            </div>
          </>
        )}
        {scorer.phase === "recording" && (
          <div className="qcard__rec" role="status" aria-live="polite">
            <span className="qcard__rec-dot" />
            <span className="qcard__rec-bars" aria-hidden="true">
              {Array.from({ length: 16 }).map((_, i) => (
                <span
                  key={i}
                  className="qcard__rec-bar"
                  ref={(el) => {
                    if (el) recBarsRef.current[i] = el;
                  }}
                  style={{ height: "30%" }}
                />
              ))}
            </span>
            <span className="qcard__rec-lbl">{t("story.sentence.listening")}</span>
          </div>
        )}
        {scorer.phase === "scoring" && (
          <div className="qcard__eval" role="status" aria-live="polite">
            <span className="qcard__eval-spin" aria-hidden="true" />
            <span className="qcard__eval-lbl">{t("story.sentence.evaluating")}</span>
          </div>
        )}
        {(filled || scorer.phase === "scored") && (
          <div className="qcard__result">
            <span className="qcard__verdict">
              {revealed ? (
                <>
                  {t("story.finish.quiz.cloze.wasRevealed", { answer: q.answer })}
                </>
              ) : isCorrect ? (
                <em>{t("story.finish.quiz.cloze.nailed")}</em>
              ) : (
                <>
                  {t("story.finish.quiz.cloze.close", { answer: q.answer })}
                </>
              )}
            </span>
            <button
              type="button"
              className="fin-btn fin-btn--primary qcard__next"
              onClick={onNext}
            >
              {isLast ? t("story.finish.quiz.toSummary") : t("story.finish.quiz.next")}{" "}
              <span className="fin-arr">→</span>
            </button>
          </div>
        )}
      </footer>
    </article>
  );
}

/* ============================================================
   Shadow question — Klara plays, user repeats. Per-token scoring.
   ============================================================ */

interface ShadowProps {
  q: ShadowQuizItem;
  story: Story;
  onAnswered: (r: Omit<QuizResult, "index" | "qType">) => void;
  onNext: () => void;
  isLast: boolean;
}

function ShadowQuestion({
  q,
  story,
  onAnswered,
  onNext,
  isLast,
}: ShadowProps): JSX.Element {
  const { t } = useTranslation();
  const [played, setPlayed] = useState(false);
  const scorer = useMicScorer(q.sentence, story.target_language);
  const recBarsRef = useRef<HTMLSpanElement[]>([]);

  // Compute tokenized rendering with per-token scoring
  const tokens = useMemo(() => tokenizeWords(q.sentence), [q.sentence]);
  const bands = scorer.result?.bands ?? null;

  const onPlay = () => {
    setPlayed(true);
    speak(q.sentence, story.target_language);
  };

  const onMicClick = () => {
    if (!played) return;
    if (scorer.phase === "recording") void scorer.stop();
    else if (scorer.phase === "idle" || scorer.phase === "error") void scorer.start();
  };

  // Live RMS bars
  useEffect(() => {
    if (scorer.phase !== "recording" || !scorer.analyser) return;
    const analyser = scorer.analyser;
    return startAudioBars(analyser, recBarsRef.current);
  }, [scorer.phase, scorer.analyser]);

  // Persist + bubble up once scored
  const reportedRef = useRef(false);
  useEffect(() => {
    if (scorer.phase !== "scored" || !scorer.result || reportedRef.current) return;
    reportedRef.current = true;
    const goodCount = Object.values(scorer.result.bands).filter((v) => v === "good").length;
    const correct = goodCount >= Math.ceil(Object.keys(scorer.result.bands).length / 2);
    onAnswered({ correct, revealed: false });
    void api
      .recordPronunciationAttempt(story.id, {
        sentence_index: -1,
        reference_text: q.sentence,
        recognized_text: scorer.result.recognizedText,
        overall_score: scorer.result.overallScore,
        word_bands: Object.fromEntries(
          Object.entries(scorer.result.bands).map(([k, v]) => [k, v]),
        ),
      })
      .catch(() => undefined);
  }, [onAnswered, q.sentence, scorer.phase, scorer.result, story.id]);

  const verdict = useMemo(() => {
    if (!bands) return null;
    const totalBands = Object.keys(bands).length;
    if (totalBands === 0) return null;
    const good = Object.values(bands).filter((v) => v === "good").length;
    if (good === totalBands) return t("story.finish.quiz.shadow.verdict.full");
    if (good >= Math.ceil(totalBands * 0.7))
      return t("story.finish.quiz.shadow.verdict.most");
    if (good >= Math.ceil(totalBands * 0.4))
      return t("story.finish.quiz.shadow.verdict.half");
    return t("story.finish.quiz.shadow.verdict.retry");
  }, [bands, t]);

  return (
    <article className="qcard" data-type="shadow">
      <header className="qcard__head">
        <span className="fin-cap">{q.cap}</span>
      </header>
      <div className="qcard__body">
        <div className="qcard__shadow-head">
          <button
            type="button"
            className="qcard__play"
            data-on={played ? "true" : undefined}
            onClick={onPlay}
            aria-label={
              played ? t("story.finish.quiz.shadow.replay") : t("story.finish.quiz.shadow.play")
            }
          >
            <span className="qcard__play-tri" />
          </button>
          <div className="qcard__shadow-body">
            <p className="qcard__klara-line">{t("story.finish.quiz.cloze.klaraSays")}</p>
            <p className="qcard__shadow-sentence" data-played={played ? "true" : undefined}>
              {bands
                ? tokens.map((tok, i) =>
                    tok.type === "word" ? (
                      <span
                        key={i}
                        className="qcard__shadow-tok"
                        data-score={bands[i]}
                      >
                        {tok.text}
                      </span>
                    ) : (
                      <span key={i}>{tok.text}</span>
                    ),
                  )
                : played
                  ? q.sentence
                  : t("story.finish.quiz.shadow.tapToHear")}
            </p>
            {q.en && <p className="qcard__en">{q.en}</p>}
          </div>
        </div>
      </div>
      <footer className="qcard__foot">
        {scorer.phase === "idle" && !bands && (
          <div className="qcard__voicebar">
            <span className="qcard__hint">
              {played
                ? t("story.finish.quiz.shadow.repeat")
                : t("story.finish.quiz.shadow.listenFirst")}
            </span>
            <button
              type="button"
              className="qcard__mic"
              onClick={onMicClick}
              disabled={!played}
            >
              <span className="fin-mic" />
              <span>{t("story.finish.quiz.shadow.repeatBtn")}</span>
            </button>
          </div>
        )}
        {scorer.phase === "recording" && (
          <div className="qcard__rec" role="status" aria-live="polite">
            <span className="qcard__rec-dot" />
            <span className="qcard__rec-bars" aria-hidden="true">
              {Array.from({ length: 16 }).map((_, i) => (
                <span
                  key={i}
                  className="qcard__rec-bar"
                  ref={(el) => {
                    if (el) recBarsRef.current[i] = el;
                  }}
                  style={{ height: "30%" }}
                />
              ))}
            </span>
            <span className="qcard__rec-lbl">{t("story.sentence.listening")}</span>
          </div>
        )}
        {scorer.phase === "scoring" && (
          <div className="qcard__eval" role="status" aria-live="polite">
            <span className="qcard__eval-spin" aria-hidden="true" />
            <span className="qcard__eval-lbl">{t("story.sentence.evaluating")}</span>
          </div>
        )}
        {scorer.phase === "scored" && bands && (
          <>
            <div className="qcard__shadow-result">
              <span className="qcard__verdict">
                <em>{verdict}</em>
              </span>
              <div className="qcard__shadow-legend">
                <span className="qcard__leg" data-tone="good">
                  {countBand(bands, "good")} {t("story.finish.quiz.shadow.legend.clear")}
                </span>
                <span className="qcard__leg" data-tone="ok">
                  {countBand(bands, "ok")} {t("story.finish.quiz.shadow.legend.ok")}
                </span>
                <span className="qcard__leg" data-tone="bad">
                  {countBand(bands, "bad")} {t("story.finish.quiz.shadow.legend.bad")}
                </span>
              </div>
            </div>
            {q.after && <p className="qcard__after">{q.after}</p>}
            <button
              type="button"
              className="fin-btn fin-btn--primary qcard__next"
              onClick={onNext}
            >
              {isLast ? t("story.finish.quiz.toSummary") : t("story.finish.quiz.next")}{" "}
              <span className="fin-arr">→</span>
            </button>
          </>
        )}
      </footer>
    </article>
  );
}

/* ============================================================
   Gender cloze question — 3-button tap picker (der/die/das),
   graded server-side.
   ============================================================ */

interface GenderClozeProps {
  q: GenderClozeQuizItem;
  story: Story;
  onAnswered: (r: Omit<QuizResult, "index" | "qType">) => void;
  onNext: () => void;
  isLast: boolean;
}

function GenderClozeQuestion({
  q,
  story,
  onAnswered,
  onNext,
  isLast,
}: GenderClozeProps): JSX.Element {
  return (
    <GenderPicker
      lemma={q.lemma}
      en={q.en}
      onGrade={(article) =>
        api.recordGenderAttempt(story.id, { vocab_item_id: q.vocab_item_id, picked_article: article })
      }
      onResult={(correct) => onAnswered({ correct, revealed: false })}
      onNext={onNext}
      isLast={isLast}
    />
  );
}

/* ============================================================
   SUMMARY
   ============================================================ */

interface SummaryProps {
  story: Story;
  scoresBySentence: Record<number, PronScores>;
  quizResults: QuizResult[];
  quizSkipped: boolean;
  reviewIds: Set<string>;
  adding: string | null;
  onToggleReview: (word: StoryWord) => void;
  onRestart: () => void;
  onNew: () => void;
  onNextInModule?: () => void;
  onHome: () => void;
  onBackToQuiz: (() => void) | null;
}

function Summary({
  story,
  scoresBySentence,
  quizResults,
  quizSkipped,
  reviewIds,
  adding,
  onToggleReview,
  onRestart,
  onNew,
  onNextInModule,
  onHome,
  onBackToQuiz,
}: SummaryProps): JSX.Element {
  const { t } = useTranslation();
  const sentences = story.content.sentences;

  const sentencesPracticed = Object.keys(scoresBySentence).length;
  const allBands = Object.values(scoresBySentence).flatMap((s) => Object.values(s));
  const clarityPct = allBands.length
    ? Math.round((allBands.filter((v) => v === "good").length / allBands.length) * 100)
    : null;

  const quizCorrect = quizResults.filter((r) => r.correct).length;
  const quizTotal = quizResults.length;

  // Souvenir: pick the sentence with the most `good` bands; tie-break longest.
  const souvenirIdx = useMemo(() => {
    let bestIdx = 0;
    let bestGood = -1;
    let bestLen = -1;
    sentences.forEach((s, i) => {
      const bands = scoresBySentence[i];
      const good = bands ? Object.values(bands).filter((v) => v === "good").length : 0;
      const len = s.target.length;
      if (good > bestGood || (good === bestGood && len > bestLen)) {
        bestIdx = i;
        bestGood = good;
        bestLen = len;
      }
    });
    return bestIdx;
  }, [scoresBySentence, sentences]);
  const souvenir = sentences[souvenirIdx];

  // Schedule: each target word with a struggled-today tag if any sentence
  // containing the word had a `bad` band on that word's token.
  const struggled = useMemo(() => {
    const set = new Set<string>();
    const lowerLemmas = story.target_words.map((w) => ({
      id: w.id,
      lemma: w.lemma.toLowerCase(),
    }));
    sentences.forEach((s, i) => {
      const bands = scoresBySentence[i];
      if (!bands) return;
      const sentenceLower = s.target.toLowerCase();
      for (const w of lowerLemmas) {
        if (!sentenceLower.includes(w.lemma)) continue;
        // Word appears in sentence. Mark struggled only if any band in this
        // sentence is "bad" — proxy for "user had trouble with this sentence".
        if (Object.values(bands).includes("bad")) set.add(w.id);
      }
    });
    return set;
  }, [scoresBySentence, sentences, story.target_words]);

  // Insight: async fetch with skeleton
  const [insight, setInsight] = useState<InsightResponse | null>(null);
  const [insightLoading, setInsightLoading] = useState(true);
  useEffect(() => {
    let cancelled = false;
    api
      .getStoryInsight(story.id)
      .then((r) => {
        if (cancelled) return;
        setInsight(r);
      })
      .catch(() => {
        // best-effort: section just doesn't show
      })
      .finally(() => {
        if (!cancelled) setInsightLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [story.id]);

  // L1 gender-transfer notes (ES→DE): async, best-effort. Empty → section hidden.
  const [l1Notes, setL1Notes] = useState<L1GenderNote[]>([]);
  useEffect(() => {
    let cancelled = false;
    api
      .getStoryL1Notes(story.id)
      .then((r) => {
        if (!cancelled) setL1Notes(r.notes);
      })
      .catch(() => {
        // best-effort: section just doesn't show
      });
    return () => {
      cancelled = true;
    };
  }, [story.id]);

  // Schedule: real SRS state per target word. While loading, fall back to
  // the heuristic so the section doesn't pop in late.
  const [schedule, setSchedule] = useState<Map<string, ScheduleEntry> | null>(null);
  useEffect(() => {
    let cancelled = false;
    api
      .getStorySchedule(story.id)
      .then((r) => {
        if (cancelled) return;
        setSchedule(new Map(r.entries.map((e) => [e.vocab_item_id, e])));
      })
      .catch(() => {
        // best-effort: stays on heuristic labels
      });
    return () => {
      cancelled = true;
    };
  }, [story.id]);

  // Klara Note: one-line teaser for tomorrow. Skeleton while loading;
  // nothing rendered if generation fails.
  const [klaraNote, setKlaraNote] = useState<KlaraNoteResponse | null>(null);
  const [klaraNoteLoading, setKlaraNoteLoading] = useState(true);
  useEffect(() => {
    let cancelled = false;
    api
      .getStoryKlaraNote(story.id)
      .then((r) => {
        if (!cancelled) setKlaraNote(r);
      })
      .catch(() => {
        // best-effort
      })
      .finally(() => {
        if (!cancelled) setKlaraNoteLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [story.id]);

  return (
    <main className="k-page finish-flow">
      <div className="fin-back-row">
        <button type="button" className="fin-back" onClick={onHome}>
          {t("common.backHome")}
        </button>
        {onBackToQuiz && (
          <button type="button" className="fin-back fin-back--right" onClick={onBackToQuiz}>
            {t("story.finish.summary.backToQuiz")}
          </button>
        )}
      </div>

      <header className="fin-hero">
        <div className="fin-hero__cap">
          <span className="fin-hero__k">K</span>
          <span className="fin-hero__cap-text">{t("story.finish.summary.cap")}</span>
        </div>
        <h1 className="fin-hero__title">{story.title}.</h1>
        <p className="fin-hero__meta">
          <span>
            <strong>{sentencesPracticed}</strong>
            {" / "}
            <strong>{sentences.length}</strong> {t("story.finish.summary.sentencesPronounced")}
          </span>
          {clarityPct !== null && (
            <>
              <span className="fin-hero__sep">·</span>
              <span>
                <strong>{clarityPct}%</strong> {t("story.finish.summary.clear")}
              </span>
            </>
          )}
          {!quizSkipped && quizTotal > 0 && (
            <>
              <span className="fin-hero__sep">·</span>
              <span>
                <strong>{quizCorrect}</strong>
                {" / "}
                <strong>{quizTotal}</strong> {t("story.finish.summary.questions")}
              </span>
            </>
          )}
        </p>
      </header>

      {souvenir && (
        <>
          <hr className="fin-rule" />
          <section className="fin-souvenir" aria-label={t("story.finish.summary.souvenir.title")}>
            <span className="fin-cap">{t("story.finish.summary.souvenir.title")}</span>
            <blockquote className="fin-souvenir__quote">
              <span className="fin-souvenir__mark">«</span>
              {souvenir.target}
              <span className="fin-souvenir__mark">»</span>
            </blockquote>
            <p className="fin-souvenir__sub">
              {t("story.finish.summary.souvenir.sub")}
              {souvenir.native && (
                <span className="fin-souvenir__en"> — {souvenir.native}</span>
              )}
            </p>
          </section>
        </>
      )}

      <hr className="fin-rule" />

      <div className="fin-twocol">
        <section className="fin-sched" aria-label={t("story.finish.summary.schedule.title")}>
          <header className="fin-sched__head">
            <span className="fin-cap">{t("story.finish.summary.schedule.title")}</span>
            <span className="fin-sched__count">
              {t("story.finish.summary.schedule.count", { count: story.target_words.length })}
            </span>
          </header>
          <ul className="fin-sched__list">
            {story.target_words.map((w) => {
              const isStruggled = struggled.has(w.id);
              const showArticle = story.target_language === "de";
              const article = showArticle ? w.gender : null;
              const added = reviewIds.has(w.id);
              const entry = schedule?.get(w.id) ?? null;
              const label = scheduleLabel(t, entry, {
                struggled: isStruggled,
                justAdded: added,
              });
              return (
                <li
                  key={w.id}
                  className="fin-sched__item"
                  data-struggled={isStruggled || undefined}
                >
                  <div className="fin-sched__word">
                    {article && <span className="fin-sched__art">{article}</span>}
                    <span className="fin-sched__lemma">{w.lemma}</span>
                    {isStruggled && (
                      <span className="fin-sched__tag">
                        {t("story.finish.summary.schedule.struggled")}
                      </span>
                    )}
                  </div>
                  <span className="fin-sched__tx">{w.translation ?? ""}</span>
                  <span className="fin-sched__next">
                    <span className="fin-sched__next-dot" />
                    {label}
                    {!added && entry && !entry.has_card && (
                      <button
                        type="button"
                        className="qcard__ghost"
                        onClick={() => onToggleReview(w)}
                        disabled={adding === w.id}
                        style={{ marginLeft: 10 }}
                      >
                        {adding === w.id
                          ? t("story.end.words.adding")
                          : t("story.end.words.add")}
                      </button>
                    )}
                  </span>
                </li>
              );
            })}
          </ul>
        </section>

        <section className="fin-insight" aria-label={t("story.finish.summary.insight.title")}>
          <span className="fin-cap">{t("story.finish.summary.insight.title")}</span>
          {insightLoading ? (
            <div className="fin-insight__skeleton" aria-busy="true">
              <div className="fin-insight__skeleton-row" />
              <div className="fin-insight__skeleton-row" />
              <div className="fin-insight__skeleton-row" />
              <div className="fin-insight__skeleton-row" />
            </div>
          ) : insight ? (
            <>
              <h3 className="fin-insight__title">{insight.title}</h3>
              <p className="fin-insight__body">{insight.body}</p>
            </>
          ) : (
            <p className="fin-insight__body">
              {t("story.finish.summary.insight.unavailable")}
            </p>
          )}
        </section>
      </div>

      {l1Notes.length > 0 && (
        <>
          <hr className="fin-rule" />
          <section className="fin-l1" aria-label={t("story.finish.summary.l1Notes.title")}>
            <span className="fin-cap">{t("story.finish.summary.l1Notes.title")}</span>
            <p className="fin-l1__hint">{t("story.finish.summary.l1Notes.hint")}</p>
            <ul className="fin-l1__list">
              {l1Notes.map((n) => (
                <li key={n.lemma} className="fin-l1__item">
                  <span className="fin-l1__word">
                    {n.gender} {n.lemma}
                  </span>{" "}
                  {n.note}
                </li>
              ))}
            </ul>
          </section>
        </>
      )}

      {(klaraNoteLoading || klaraNote) && (
        <>
          <hr className="fin-rule" />
          <section className="fin-note" aria-label={t("story.finish.summary.note.aria")}>
            {klaraNoteLoading ? (
              <div className="fin-note__skeleton" aria-busy="true">
                <div className="fin-note__skeleton-row" />
              </div>
            ) : klaraNote ? (
              <>
                <p className="fin-note__body">
                  <span className="fin-note__open">«</span>
                  {klaraNote.body}
                  <span className="fin-note__close">»</span>
                </p>
                <p className="fin-note__sign">— K</p>
              </>
            ) : null}
          </section>
        </>
      )}

      <hr className="fin-rule" />

      <nav className="fin-cta">
        {onNextInModule && (
          <button type="button" className="fin-btn fin-btn--primary" onClick={onNextInModule}>
            {t("story.end.cta.nextInModule")} <span className="fin-arr">→</span>
          </button>
        )}
        <button
          type="button"
          className={onNextInModule ? "fin-btn" : "fin-btn fin-btn--primary"}
          onClick={onNew}
        >
          {t("story.end.cta.another")} <span className="fin-arr">→</span>
        </button>
        <button type="button" className="fin-btn fin-btn--ghost" onClick={onRestart}>
          {t("story.end.cta.reread")}
        </button>
      </nav>
    </main>
  );
}

/* ============================================================
   Helpers
   ============================================================ */

interface Tok {
  type: "word" | "space" | "punct";
  text: string;
}

function tokenizeWords(text: string): Tok[] {
  const re = /(\s+)|([.,!?;:„“”»«()¡¿—–\-]+)|([^\s.,!?;:„“”»«()¡¿—–\-]+)/g;
  const out: Tok[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    if (m[1]) out.push({ type: "space", text: m[1] });
    else if (m[2]) out.push({ type: "punct", text: m[2] });
    else if (m[3]) out.push({ type: "word", text: m[3] });
  }
  return out;
}

function countBand(bands: Record<number, ScoreBand>, band: ScoreBand): number {
  return Object.values(bands).filter((v) => v === band).length;
}

/**
 * Render the SRS schedule label for one word.
 *
 * Priority (overrides cascade down):
 *   1. Just-added in this session   → "Añadida"
 *   2. Schedule data not yet loaded → fall back to the in-session heuristic
 *      (struggled → "Próxima sesión" else "Pendiente")
 *   3. No SRS card at all           → "+ Añadir a repaso" CTA caller renders
 *   4. Real bucket from the backend → localised label per bucket
 */
function scheduleLabel(
  t: (key: string) => string,
  entry: ScheduleEntry | null,
  ctx: { struggled: boolean; justAdded: boolean },
): string {
  if (ctx.justAdded) return t("story.finish.summary.schedule.added");
  if (entry === null) {
    return ctx.struggled
      ? t("story.finish.summary.schedule.nextSession")
      : t("story.finish.summary.schedule.later");
  }
  if (!entry.has_card) {
    return t("story.finish.summary.schedule.notInSrs");
  }
  const map: Record<ScheduleBucket, string> = {
    not_in_srs: t("story.finish.summary.schedule.notInSrs"),
    due_now: t("story.finish.summary.schedule.dueNow"),
    soon: t("story.finish.summary.schedule.soon"),
    this_week: t("story.finish.summary.schedule.thisWeek"),
    next_week: t("story.finish.summary.schedule.nextWeek"),
    later: t("story.finish.summary.schedule.later"),
  };
  return map[entry.bucket];
}

/** Case + diacritic insensitive equality. "AUTOBÚS" === "autobus". */
function matchesLoose(a: string, b: string): boolean {
  const normalize = (s: string) =>
    s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().trim();
  return normalize(a).includes(normalize(b)) || normalize(b).includes(normalize(a));
}
